spring:
  application:
    name: customer-service

server:
  port: 8080
  servlet:
    context-path: /customer-service

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} | %-5level | %logger{36} | X-Request-Id [%X{requestId}] | X-Client-Id [%X{clientId}] | %msg%n"
  level:
    root: INFO