openapi: 3.0.3
info:
  title: Customer Service API
  version: 0.0.1
  contact:
    name: API Support
    email: guilherme_gmc@outlook.com

servers:
  - url: http://localhost:8080/customer-service
    description: Local development server
  - url: http://localhost:8080/customer-service
    description: Cloud test server

paths:
  /customers:
    post:
      tags:
        - Customers
      summary: Register a new customer
      operationId: createCustomer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerRegisterRequest'
      responses:
        '201':
          description: Customer successfully created
          headers:
            Location:
              description: URL of the newly created resource
              schema:
                type: string
                example: /customers/550e8400-e29b-41d4-a716-446655440000
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerRegisterResponse'
        '400':
          description: Invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerRegisterErrorResponse'
        '409':
          description: CPF or email already registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerRegisterErrorResponse'
              example:
                details:
                  - field: "cpf"
                    status: "CPF already registered."
                  - field: "email"
                    status: "Email already registered."
                message: "INVALID_DATA"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
#    get:
#      tags:
#        - Customers
#      summary: Retrieve a customer by ID
#      operationId: getCustomerById
#      parameters:
#        - name: customerId
#          in: path
#          required: true
#          schema:
#            type: string
#            format: uuid
#          description: Unique identifier of the customer
#      responses:
#        '200':
#          description: Customer retrieved successfully
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/CustomerResponse'
#        '404':
#          description: Customer not found
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/ErrorResponse'
#        '500':
#          description: Internal server error
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/ErrorResponse'
#    put:
#      tags:
#        - Customers
#      summary: Update an existing customer
#      operationId: updateCustomer
#      parameters:
#        - name: customerId
#          in: path
#          required: true
#          schema:
#            type: string
#            format: uuid
#          description: Unique identifier of the customer
#      requestBody:
#        required: true
#        content:
#          application/json:
#            schema:
#              $ref: '#/components/schemas/CustomerRegisterRequest'
#      responses:
#        '200':
#          description: Customer updated successfully
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/CustomerResponse'
#        '400':
#          description: Invalid data in request body
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/CustomerRegisterErrorResponse'
#        '404':
#          description: Customer not found
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/ErrorResponse'
#        '500':
#          description: Internal server error
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/ErrorResponse'

  /login:
    post:
      tags:
        - Authentication
      summary: Authenticate a customer
      operationId: authenticateCustomer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerLoginRequest'
            examples:
              loginWithCpf:
                summary: Login using CPF
                value:
                  identifier: "12345678901"
                  password: "Password123@"
              loginWithEmail:
                summary: Login using email
                value:
                  identifier: "john@example.com"
                  password: "Password123@"
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerLoginResponse'
        '400':
          description: Bad request (malformed data)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerLoginErrorResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerLoginErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    CustomerRegisterRequest:
      type: object
      required:
        - cpf
        - email
        - name
        - phone
        - birthDate
        - gender
        - password
      properties:
        cpf:
          type: string
          example: "12345678901"
          minLength: 11
          maxLength: 11
          pattern: '^[0-9]{11}$'
          description: Customer's CPF (Brazilian tax ID).
        email:
          type: string
          format: email
          example: "john@example.com"
          minLength: 5
          maxLength: 200
          description: Customer's email.
        name:
          type: string
          example: "Guilherme Mendes"
          minLength: 5
          maxLength: 80
          description: Full name of the customer.
        phone:
          type: string
          example: "11999998888"
          minLength: 11
          maxLength: 11
          pattern: '^[0-9]{10,11}$'
          description: Customer's mobile phone number including area code (DDD).
        birthDate:
          type: string
          format: date
          example: "1990-01-01"
          description: Customer's date of birth.
        gender:
          type: string
          enum:
            - MALE
            - FEMALE
            - OTHER
            - PREFER_NOT_TO_SAY
          description: Customer's gender.
        password:
          type: string
          format: password
          minLength: 8
          maxLength: 20
          pattern: '^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[!@#$%^&*()_+]).{8,}$'
          example: "R8m!tQ2_pL9"
          description: Password must contain at least one uppercase letter, one lowercase letter, one number, and one special character from !@#$%^&*()_+.

    CustomerRegisterResponse:
      type: object
      properties:
        details:
          type: object
          properties:
            customerId:
              type: string
              format: uuid
              example: "b19c1d76-02cc-4f7f-8233-928f2a3a55ff"
            createdAt:
              type: string
              format: date
        message:
          type: string
          enum:
            - CUSTOMER_CREATED_SUCCESSFULLY

    CustomerRegisterErrorResponse:
      type: object
      properties:
        details:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
                example: "cpf"
              status:
                type: string
                example: "Invalid CPF."
        message:
          type: string
          enum:
            - INVALID_DATA

    CustomerResponse:
      type: object
      required:
        - customerId
        - cpf
        - email
        - name
        - phone
        - birthDate
        - gender
        - createdAt
        - updatedAt
      properties:
        customerId:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        cpf:
          type: string
          example: "12345678901"
        email:
          type: string
          example: "john@example.com"
        name:
          type: string
          example: "John Doe"
        phone:
          type: string
          example: "11999998888"
        birthDate:
          type: string
          format: date
          example: "1990-01-01"
        gender:
          type: string
          enum:
            - MALE
            - FEMALE
            - OTHER
            - PREFER_NOT_TO_SAY
        createdAt:
          type: string
          format: date-time
          example: "2025-10-15T19:35:42Z"
        updatedAt:
          type: string
          format: date-time
          example: "2025-10-21T18:45:12Z"

    CustomerLoginRequest:
      type: object
      required:
        - identifier
        - password
      properties:
        identifier:
          type: string
          example: "john@example.com"
          description: "May be either the user's email or CPF."
          minLength: 5
          maxLength: 200
        password:
          type: string
          format: password
          example: "Password123@"
          pattern: '^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[!@#$%^&*()_+]).{8,}$'
          minLength: 8
          maxLength: 20

    CustomerLoginResponse:
      type: object
      required:
        - token
        - tokenType
        - expiration
        - clientId
      properties:
        token:
          type: string
          description: JWT authentication token
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        tokenType:
          type: string
          example: "Bearer"
        expiration:
          type: string
          format: date-time
          example: "2025-10-15T20:00:00Z"
        clientId:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"

    CustomerLoginErrorResponse:
      type: object
      properties:
        message:
          type: string
          enum:
            - INVALID_CREDENTIALS
            - INVALID_DATA
          example: "INVALID_CREDENTIALS"
        details:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
                example: "identifier"
              status:
                type: string
                example: "Invalid CPF."

    ErrorResponse:
      type: object
      required:
        - timestamp
        - path
        - message
        - traceId
      properties:
        timestamp:
          type: string
          format: date-time
          example: "2025-10-15T19:35:42Z"
        error:
          type: string
          example: "Internal Server Error"
          description: Short error description.
        message:
          type: string
          example: "Unexpected error while processing the request."
          description: More detailed error message.
        path:
          type: string
          example: "/users"
          description: Endpoint path where the error occurred.
        traceId:
          type: string
          format: uuid
          example: "b5a8e2c8-3e54-4f73-a2b0-f9b1dbfa34cc"
          description: Request ID for log and monitoring tracking.